baseURL: 'https://kouwtkz-site.web.app/'
languageCode: 'ja'
title: 'わたかぜっこ'
maxView: 256
description: '『わたかぜコウ』のポートフォリオサイト。気まぐれに様々なイラストや作品を載せてます。'
short:
  description: 'わたかぜコウのポートフォリオサイト'
icon:
  path: '/icons/icon.png'
  size: ['48x48', '180x180', '192x192', '256x256', '512x512']
manifest:
  background_color: "#c1d64c"
  path: '/manifest.json'
google:
# とりあえず前のサイトのやーつ
  analytics: "G-5ZTX38MD12"
devide:
  menu:
    setting: 'app'

enableEmoji: true
enableRobotsTXT: true
setupSound: 'NewLeafLoad_2lp.m4a'
